version: "3.5"
services:
  nodered:
    build: .
    container_name: nodered
    privileged: true
    restart: unless-stopped
    network_mode: host
    stdin_open: true 
    tty: true
    environment:
      - TZ=Europe/London
    volumes:
      - nodered_data:/data:rw
#    healthcheck:
#      test: netstat -an | grep 1880; if [ 0 != $$? ]; then exit 1; fi;
##      test: ["CMD", "curl", "-f", "http://localhost:1880"]
#      interval: 30s
#      timeout: 20s
#      retries: 3
#      start_period: 40s
    labels:
#      - "com.centurylinklabs.watchtower.enable=true"
volumes:
  nodered_data:
    external: true
