version: "3.5"
services:
  nodered:
    build: .
    container_name: nodered
    privileged: true
    restart: unless-stopped
    network_mode: host
    stdin_open: true 
    tty: true
    environment:
      - TZ=Europe/London
    volumes:
      - nodered_data:/data:rw
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1880"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
volumes:
  nodered_data:
    external: true
