version: "3.5"
services:
  nodered:
    build: .
    container_name: nodered-debian
    privileged: true
    restart: unless-stopped
    network_mode: host
    stdin_open: true 
    tty: true
    environment:
      - TZ=Europe/London
    volumes:
      - nodered_data:/data:rw
volumes:
  nodered_data:
    external: true
